[package]
name = "rust_pswd_manager"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
chacha20poly1305 = { version = "0.9.0", features = ["stream"] }
sha2 = "0.10.8"
anyhow = "1.0.91"
